---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ferdium.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: ferdium-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: ferdium-server
  template:
    metadata:
      labels:
        app.kubernetes.io/component: ferdium-server
    spec:
      containers:
        - name: ferdium-server
          image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3333
          volumeMounts:
            - name: ferdium-server-data
              mountPath: /data
            - name: ferdium-server-reciepes
              mountPath: /app/build/recipes
          env:
            - name: NODE_ENV
              value: "{{ .Values.config.nodeEnv }}"
            - name: APP_URL
              value: "{{ .Values.config.appURL }}"
            - name: DB_CONNECTION
              value: "{{ .Values.config.db.connection }}"
            - name: DB_HOST
              value: "{{ .Values.config.db.host }}"
            - name: DB_PORT
              value: "{{ .Values.config.db.port }}"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "ferdium-server.fullname" . }}-secret-config
                  key: dbUser
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "ferdium-server.fullname" . }}-secret-config
                  key: dbPassword
            - name: DB_DATABASE
              value: "{{ .Values.config.db.database }}"
            - name: DB_SSL
              value: "{{ .Values.config.db.ssl }}"
            - name: MAIL_CONNECTION
              value: "{{ .Values.config.smtp.connection }}"
            - name: SMTP_HOST
              value: "{{ .Values.config.smtp.host }}"
            - name: SMTP_PORT
              value: "{{ .Values.config.smtp.port }}"
            - name: MAIL_SSL
              value: "{{ .Values.config.smtp.ssl }}"
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "ferdium-server.fullname" . }}-secret-config
                  key: smtpUsername
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "ferdium-server.fullname" . }}-secret-config
                  key: smtpPassword
            - name: MAIL_SENDER
              value: "{{ .Values.config.smtp.mailSender }}"
            - name: IS_CREATION_ENABLED
              value: "{{ .Values.config.isCreationEnabled }}"
            - name: IS_DASHBOARD_ENABLED
              value: "{{ .Values.config.isDashboardEnabled }}"
            - name: IS_REGISTRATION_ENABLED
              value: "{{ .Values.config.isRegistrationEnabled }}"
            - name: CONNECT_WITH_FRANZ
              value: "{{ .Values.config.connectWithFranz }}"
            - name: DATA_DIR
              value: "{{ .Values.config.dataDir }}"
            - name: JWT_USE_PEM
              value: "{{ .Values.config.jwtUsePem }}"
      volumes:
        - name: ferdium-server-data
          persistentVolumeClaim:
            claimName: {{ include "ferdium-server.fullname" . }}-data-pvc
        - name: ferdium-server-reciepes
          persistentVolumeClaim:
            claimName: {{ include "ferdium-server.fullname" . }}-reciepes-pvc
