---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ferdium.fullname" . }}-secret-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: ferdium-server
type: Opaque
data:
  smtpUsername: {{ .Values.config.smtp.username | b64enc | quote }}
  smtpPassword: {{ .Values.config.smtp.password | b64enc | quote }}
  dbUser: {{ .Values.config.db.username | b64enc | quote }}
  dbPassword: {{ .Values.config.db.password | b64enc | quote }}

