---
kind: Service
apiVersion: v1
metadata:
  name: {{ include "ferdium.fullname" . }}-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: ferdium-server
spec:
  ports:
  - port: 3333
    name: webui
    protocol: TCP
  selector:
    app.kubernetes.io/component: ferdium-server